apiVersion: v1
kind: PersistentVolume
metadata:
  name: ss-pv
spec:
  capacity:
    storage: 5Gi # Set size based on your data needs
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" # Path where the volume will be stored on the cluster node
